# file devlaptopsetup.yml
# use this ansible playbook to setup a new development laptop
---
- hosts: all
  tasks:
  - name: Install mono-complete
    become: true
    apt:
      name: mono-complete
      state: present
      update_cache: true
  - name: Install basic ubuntu desktop
    become: true
    apt:
      name: ubuntu-desktop
      state: latest
      install_recommends: no
  - name: Change grub text line
    become: true
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="text"'
  - name: Change grub console line
    become: true
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX=console'
  - name: run update grub command
    become: true
    command: update-grub
  - name: run systemctl command
    become: true
    command: 'systemctl set-default multi-user.target'

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    become: true

  - name: Install basic list of packages
    become: true
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      state: present
      update_cache: yes

  - name: Add Docker APT repository
    become: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker packages
    apt:
      name: ['docker-ce','docker-ce-cli','containerd.io']
      state: present

  - name: Install Docker-compose 
    shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose


